apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bankadhesion-deployment
  labels:
    app: bankadhesion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankadhesion
  template:
    metadata:
      labels:
        app: bankadhesion
    spec:
      containers:
      - name: bank-adhesion
        image: akdmle/bank_api
        ports:
        - containerPort: 8000
      - name: authentification
        image: akdmle/bank_authentification
        ports:
        - containerPort: 9000
      - name: standardisation
        image: akdmle/bank_standardisation
        ports:
        - containerPort: 9001
      - name: classification
        image: akdmle/bank_classification
        ports:
        - containerPort: 9002
      - name: bulkclassification
        image: akdmle/bank_bulk_classification
        ports:
        - containerPort: 9003
